name: Generate release APK
 
 # Controls when the action will run.
on:
    workflow_dispatch:
   
jobs:
   package-release-apk:
     name: Generate release APK
     runs-on: ubuntu-latest
 
     steps:
 
       - name: Checkout code for app release
         uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '16'
       # ref:: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
 
       - name: List Directory
         run: ls
 
       - name: Install npm dependencies
         run: npm install --legacy-peer-deps
 
       - name: Generate signed APK
         run: cd android && ./gradlew app:assembleRelease
 
       - name: Upload release APK
         uses: actions/upload-artifact@v2
         with:
           name: awesome-app.apk
           path: android/app/build/outputs/apk/release/app-release.apk
